name: Test-Examples   # BSP Examples
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Test-Examples:                     # Install tools, build 
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout STM32H743I-EVAL_BSP root
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .ci

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./.ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Checkout STM32H743I-EVAL_BSP
        uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/STM32H743I-EVAL_BSP
          path: ./STM32H743I-EVAL_BSP

      - name: Checkout STM32H7xx_DFP
        uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/STM32H7xx_DFP
          path: ./STM32H7xx_DFP

      - name: Checkout CMSIS-Driver_STM32
        uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/CMSIS-Driver_STM32
          path: ./CMSIS-Driver_STM32

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Add local CMSIS packs
        run: |
          cpackget add ./STM32H743I-EVAL_BSP/Keil.STM32H743I-EVAL_BSP.pdsc
          cpackget add ./STM32H7xx_DFP/Keil.STM32H7xx_DFP.pdsc
          cpackget add ./CMSIS-Driver_STM32/ARM.CMSIS-Driver_STM32.pdsc

      - name: Copy Bliky example to .CI/Examples/
        working-directory: ./
        run: |
          mkdir -p ./CI/Examples/Blinky
          cp -rf ./STM32H743I-EVAL_BSP/Examples/Blinky/* ./CI/Examples/Blinky/

      - name: Build Blinky AC6
        if: always()      
        working-directory: ./CI/Examples/Blinky
        run: |
          cbuild ./Blinky.csolution.yml --packs --update-rte --packs --toolchain AC6 --rebuild

      - name: Upload Artifact of the Blinky AC6 build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Blinky_AC6
          path: |
            ./CI/Examples/Blinky/
            !./CI/Examples/Blinky/tmp/
          retention-days: 1

      - name: Build Blinky GCC
        if: always()      
        working-directory: ./CI/Examples/Blinky
        run: |
          rm -rf out
          rm -rf tmp
          cbuild ./Blinky.csolution.yml --packs --update-rte --packs --toolchain GCC --rebuild

      - name: Upload Artifact of the Blinky GCC build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Blinky_GCC
          path: |
              ./CI/Examples/Blinky/
              !./CI/Examples/Blinky/tmp/